export const LOGIN_STUDENT_REQUEST = "STUDENT.LOGIN_STUDENT_REQUEST";
export const LOGIN_STUDENT_SUCCESS = "STUDENT.LOGIN_STUDENT_SUCCESS";
export const LOGIN_STUDENT_FAIL = "STUDENT.LOGIN_STUDENT_FAILURE";
