export const GET_SINGLE_USER_REQUEST = "USER.GET_SINGLE_USER_REQUEST";
export const GET_SINGLE_USER_SUCCESS = "USER.GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_FAIL = "USER.GET_SINGLE_USER_FAILURE";
