export const GET_ALL_TEACHER_REQUEST = "USER.GET_ALL_TEACHER_REQUEST";
export const GET_ALL_TEACHER_SUCCESS = "USER.GET_ALL_TEACHER_SUCCESS";
export const GET_ALL_TEACHER_FAIL = "USER.GET_ALL_TEACHER_FAILURE";
