export const GET_SINGLE_STUDENT_REQUEST = "STUDENT.GET_SINGLE_STUDENT_REQUEST";
export const GET_SINGLE_STUDENT_SUCCESS = "STUDENT.GET_SINGLE_STUDENT_SUCCESS";
export const GET_SINGLE_STUDENT_FAIL = "STUDENT.GET_SINGLE_STUDENT_FAILURE";
