export const GET_ALL_SUBJECT_REQUEST = "USER.GET_ALL_SUBJECT_REQUEST";
export const GET_ALL_SUBJECT_SUCCESS = "USER.GET_ALL_SUBJECT_SUCCESS";
export const GET_ALL_SUBJECT_FAIL = "USER.GET_ALL_SUBJECT_FAILURE";
